# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee661a18ece4078987b58dace02477c6a6defaf2d46bf63505f7cc983c09631fad94f241c61407310d848b617f69db1cbef345d9bb85c5e52f4996d07d2d5a21

test:
  secret_key_base: d0ee1fc9084cdd927af698d3b499fcb8e7665e2d82ab19907a21bb3c99353357898dbc3592136e8fb876c5e3738e1fd8196aa591c7e9ce0127fba4d2b36f4b2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
